local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
STRINGS.CHARACTER_TITLES.bulingbuling = "不灵小姐"
STRINGS.CHARACTER_NAMES.bulingbuling = "BulingBuling"
STRINGS.CHARACTER_DESCRIPTIONS.bulingbuling = "*因为失眠和胃病而苦恼\n*力气极小压根没法打 \n*从出生开始就被某个存在注视着"
STRINGS.CHARACTER_QUOTES.bulingbuling = "\"科技不是第一战斗力\""
STRINGS.UI = STRINGS.UI or {}
STRINGS.UI.CRAFTING_FILTERS = STRINGS.UI.CRAFTING_FILTERS or {}
STRINGS.UI.CRAFTING_FILTERS.BLTAB = "不灵科技"
STRINGS.UI.CRAFTING_FILTERS.YJTAB = "研究项目"
STRINGS.UI.CRAFTING_FILTERS["BLTAB"] = "不灵科技"
STRINGS.UI.CRAFTING_FILTERS["YJTAB"] = "研究项目"

-- Пчелиная ферма
STRINGS.NAMES.BULING_BEE_BOX = "Автоматический Пчелиный Улей"
STRINGS.NAMES.BULING_BEE_BOX_ITEM = "Автоматический Пчелиный Улей"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_BOX = "Автоматический улей. Положите внутрь специализированных пчёл для пассивной добычи ресурсов!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_BOX_ITEM = "Автоматический улей. Разместите на земле для производства ресурсов!"

STRINGS.NAMES.BULING_BEE_MINE = "Пчела-Шахтер"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_MINE = "Добывает камни, кремень и минералы в улье."
STRINGS.NAMES.BULING_BEE_POLICE = "Пчела-Полицейский"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_POLICE = "Охраняет улей и производит свежий мёд."
STRINGS.NAMES.BULING_BEE_PIRATE = "Пиратская Пчела"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_PIRATE = "Добывает золотые самородки и сокровища."
STRINGS.NAMES.BULING_BEE_QUEEN = "Королевская Пчела"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_QUEEN = "Клонирует и размножает других пчёл в улье!"
STRINGS.NAMES.BULING_BEE_GOVERNOR = "Пчела-Губернатор"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_GOVERNOR = "Приносит золото, мёд и редкие самоцветы."
STRINGS.NAMES.BULING_BEE_STONECUTTERS = "Пчела-Каменщик"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_STONECUTTERS = "Производит обработанный камень и мрамор."
STRINGS.NAMES.BULING_BEE_GARDENER = "Пчела-Садовод"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_GARDENER = "Приносит семена и свежие овощи."
STRINGS.NAMES.BULING_BEE_CAI = "Пчела-Сборщик"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_CAI = "Собирает траву, ветки и ягоды."
STRINGS.NAMES.BULING_BEE_FISH = "Пчела-Рыбак"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_FISH = "Ловит рыбу и приносит морепродукты."
STRINGS.NAMES.BULING_BEE_SMITH = "Пчела-Кузнец"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BEE_SMITH = "Создает металл, кремень и руду."

--物品
STRINGS.NAMES.BULING_OVERCOAT = "成品服饰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_OVERCOAT= "组合出来的服装\n具体功能由配件决定"
STRINGS.NAMES.BULING_CHEST_MINI = "物流箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEST_MINI= "常见的物流设备\n用于被机械臂输入物品"
STRINGS.NAMES.BULING_CHUANSONGDAI = "标准传送带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHUANSONGDAI= "常见的物流设备\n检查可以转换方向"
STRINGS.NAMES.BULING_JIXIEBI = "机械臂传送带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIXIEBI= "常见的物流设备\n检查可以转换方向\n内置机械臂取放物品"
STRINGS.NAMES.BULING_SHUIPEI = "土培箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHUIPEI= "\n用来栽培不灵专属作物\n当作物成熟时\n会寻找附近的机械臂\n并向其输出作物"
STRINGS.NAMES.BULING_HULK = "合金巨兽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HULK= "一种强力机器人"
STRINGS.NAMES.BULING_BOOK_TONGXUNTAI = "通讯机蓝图"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BOOK_TONGXUNTAI= "可以学会一种配方"
STRINGS.NAMES.BULING_BOOK_YAJIN = "提取铔金蓝图"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BOOK_YAJIN= "可以学会一种配方"
STRINGS.NAMES.BULING_TONGXUNTAI = "通讯台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TONGXUNTAI= "可以联络到信号范围内的其他人"
STRINGS.NAMES.BULING_YAJIN = "铔金"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_YAJIN= "一种心灵金属，可以开发灵能"
STRINGS.NAMES.BULING_FABRIC = "粗纤维布"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FABRIC= "用杂草编织\n并不耐用"
STRINGS.NAMES.BULING_GOATMILK = "优质羊奶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GOATMILK= "多喝的话就可以成为巨乳了\n好诱人!"
STRINGS.NAMES.BULING_MILK_GOAT = "奶羊"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MILK_GOAT= "通过基因改良得到的产物，可以收获羊奶"
STRINGS.NAMES.BULING_YANJIUDIAN = "研究磁盘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_YANJIUDIAN= "模拟实验得到的产物，可以用来研究新的科技"
STRINGS.NAMES.BULING_YANJIUTAI = "研究台Mk1"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_YANJIUTAI= "这台电脑在不停的进行模拟实验\n以60秒/个的速度生产研究磁盘\n每次生产消耗100Bp电力"
STRINGS.NAMES.BULING_JUHEMEI_BETA = "贝塔聚合酶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JUHEMEI_BETA= "浓缩的阿尔法酶\n合成手段产率太低了\n可以从贝塔系植株上抽取"
STRINGS.NAMES.BULING_JUHEMEI_ALPHA = "阿尔法聚合酶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JUHEMEI_ALPHA= "从人工环境培养的植物中抽取的特殊材料\n可以用于对种子进行更好的改造"
STRINGS.NAMES.BULING_ZHUSHEQI = "注射器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHUSHEQI= "用于注射或抽取液体\n可以从植株中抽取聚合酶\n必须是成熟的不灵植株"
STRINGS.NAMES.BULING_ROCKY = "虾古MK-1"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ROCKY= "简易的战斗用机甲\n可部署为攻城模式\n因为材料的关系并不结实"
STRINGS.NAMES.BULING_CHIPBOX = "存储芯片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHIPBOX= "可以放入存储芯片中\n内置5x5空间\n只能在特定环境中打开\n提供打开存储芯片的环境"
STRINGS.NAMES.BULING_CONVERSION = "物质转换器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CONVERSION= "可以将能量转化为物质\n或是将物质提取为能量\n是很多东西的核心"
STRINGS.NAMES.BULING_INFINITEBOX = "次元存储装置"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_INFINITEBOX= "内置5x5空间\n提供打开存储芯片的环境\n只能放入存储芯片\n理论上提供无限存储空间"
STRINGS.NAMES.BULING_CAR_LOG = "木制小车"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAR_LOG= "粗糙的木头外壳\n内置合金箱\n还算可以的速度\n轮子偶尔会卡住"
STRINGS.NAMES.BULING_WATERPROOF_FIELD = "防水力场"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WATERPROOF_FIELD= "隔绝普通雨水和雾气\n充满电可工作4.5天\n发光并绝缘\n但是力场会妨碍建造"
STRINGS.NAMES.BULING_ZIDONGHECHENG = "自动合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZIDONGHECHENG= "在左侧放好成品\n中间放入原料\n右边输出成品\n生产时间2秒，耗电25/次\n可以接入自动化流水线"
STRINGS.NAMES.BULING_PILIANGHECHENG = "批量合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PILIANGHECHENG= "已移除"
STRINGS.NAMES.BULING_DIANXIANGAN = "电力输送端"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANXIANGAN= "可以储存1000Bp电力\n只向中继器输电\n可以被供电\n这是电线杆。。吧"
STRINGS.NAMES.BULING_BILEIZHEN = "避雷针控制模块"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BILEIZHEN= "可以储存2000Bp电力\n被雷劈时产电200Bp\n只向中继器输电\n这是避雷剑。。吧"
STRINGS.NAMES.BULING_CORE = "高级机器核心"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CORE= "非常精密\n用来制作高级机器"
STRINGS.NAMES.BULING_GUN_ZERO = "激光手枪-零式"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_ZERO= "非常普通的激光枪\n需要装载4个部件才能工作\n没有特殊功能"
STRINGS.NAMES.BULING_GUN_WHITE = "格林冲锋枪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_WHITE= "按住右键连发\n短时间倾泻大量火力\n需要装载4个部件才能工作\n适合狩猎大型生物"
STRINGS.NAMES.BULING_GUN_YANG = "脉冲手枪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_YANG= "每次攻击会自充电5Bp\n需要装载4个部件才能工作\n适合用于狩猎小型生物"
STRINGS.NAMES.BULING_GUN_QING = "轻型手枪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_QING= "改进了枪械材料\n需要装载4个部件才能工作\n装备移动速度增加40%"
STRINGS.NAMES.BULING_GUN_QIANGGUAN = "标准枪管"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_QIANGGUAN= "普通枪管\n伤害20,能耗10\n非常标准"
STRINGS.NAMES.BULING_GUN_JIGUANG = "激光引导器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_JIGUANG= "校准激光\n没有什么特别的"
STRINGS.NAMES.BULING_FENGRENJI = "缝纫机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENGRENJI= "用来制作新衣服"
STRINGS.NAMES.BULING_GUN_DIANCHI = "制式电池"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_DIANCHI= "普通电池\n100点能量上限\n非常标准\n用充电器充电"
STRINGS.NAMES.BULING_GUN_SHOUBING = "普通手柄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_SHOUBING= "没什么特别的\n攻击距离15\n握着不是很舒服"
STRINGS.NAMES.BULING_GUN_QIANGGUAN_YANG = "阳极枪管"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_QIANGGUAN_YANG= "大功率枪管\n伤害49,能耗30\n伤害增加"
STRINGS.NAMES.BULING_GUN_QIANGGUAN_YING = "阴极枪管"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_QIANGGUAN_YING= "低功率枪管\n伤害10,能耗5\n节能枪管"
STRINGS.NAMES.BULING_GUN_JIGUANG_YAOSHOU = "格拉斯引导器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_JIGUANG_YAOSHOU= "校准激光\n目标生命在80%以上时\n会额外造成1.25倍的伤害"
STRINGS.NAMES.BULING_GUN_JIGUANG_BOLI = "斯蒂普引导器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_JIGUANG_BOLI= "强化激光\n攻击时有10%的机率\n随机获取目标掉落物"
STRINGS.NAMES.BULING_GUN_DIANCHI_TONGLIANG = "通量电池"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_DIANCHI_TONGLIANG= "普通电池\n300点能量上限\n非常标准\n用充电器充电"
STRINGS.NAMES.BULING_GUN_DIANCHI_TAIYANG = "太阳能电池"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_DIANCHI_TAIYANG= "太阳能电池\n200点能量上限\n白天每5秒充电5Bp\n用充电器充电"
STRINGS.NAMES.BULING_GUN_SHOUBING_BIAOQIANG = "RO-16标枪手柄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_SHOUBING_BIAOQIANG= "能量消耗-5\n攻击距离10\n降低攻击距离"
STRINGS.NAMES.BULING_GUN_SHOUBING_JUJI = "BE-3狙击手柄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUN_SHOUBING_JUJI= "能量消耗+5\n攻击距离24\n增加攻击距离"
STRINGS.NAMES.BULING_PLAYER = "星际海盗智能人形"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLAYER= "这是边缘世界比较常见的小型机器人\n不过看起来被星际海盗改装过了"
STRINGS.NAMES.BULING_MINE = "地雷Rx2"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MINE= "普通的小地雷\n具备自动感应功能\n但是因此不是很灵敏"
STRINGS.NAMES.BULING_JIDI = "破损的降落仓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIDI= "这个降落仓内含人形制造舱\n条件允许的话我真想拆开看看"
STRINGS.NAMES.BULING_GLOMLING = "机械格罗咪飞机器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLOMLING= "因为材料问题它没有搭载太多移动以外的必要组件"
STRINGS.NAMES.BULING_CAVE_TOOL = "洞穴挖掘工具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAVE_TOOL= "需要用挖矿机工作至少10次后才能在下方建造岩洞"
STRINGS.NAMES.BULING_CAVE_ENTRANCE = "地洞"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAVE_ENTRANCE= "我看来要当阵山顶洞人了"
STRINGS.NAMES.BULING_FLOUR = "面粉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FLOUR= "萃取器精加工的产物"
STRINGS.NAMES.BULING_SYSTEM = "飞船终端"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SYSTEM= "它会告诉我该怎么做的"
STRINGS.NAMES.BULING_PLANT_ZHONGZIDING = "塞德锭植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ZHONGZIDING= "它会吸收地下的矿物质来制造塞德锭"
STRINGS.NAMES.BULING_CHEST = "合金箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEST= "结实又安全的箱子"
STRINGS.NAMES.BULING_BANSHOU = "不灵扳手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BANSHOU= "用来搬运机器"
STRINGS.NAMES.BULING_PULEIDI = "普雷蒂水晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PULEIDI= "塞德锭的奇妙结构\n能用在很多地方"
STRINGS.NAMES.BULING_PULEIDI_PLANK = "普雷蒂金属板"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PULEIDI_PLANK= "具备泛用性的板材\n缺点是韧性低"
STRINGS.NAMES.BULING_MANUAL_ITEM = "合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_MANUAL = "合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "为啥不是4个木头合成"
STRINGS.NAMES.BULING_GLASS = "塞德玻璃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLASS= "把塞德锭萃取的话\n就能得到这种便宜玻璃\n这可真是神奇"
STRINGS.NAMES.BULING_SEED_ZHONGZIDING = "塞德锭种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ZHONGZIDING= "在它长成后会源源不断的生产塞德锭"
STRINGS.NAMES.BULING_MANUAL = "不灵工作台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "它提供了3x3的合成空间供我使用"
STRINGS.NAMES.BULING_ZHONGZIDING = "塞德锭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGZIDING= "因为是可以种出来的，所以很环保\n我很青睐这种金属"
STRINGS.NAMES.BULING_RONGLU_ITEM = "萃取机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU_ITEM= "放在地上用吧"
STRINGS.NAMES.BULING_RONGLU2_ITEM = "自动萃取机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU2_ITEM= "放在地上用吧"
STRINGS.NAMES.BULING_RONGLU2 = "自动萃取机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU2= "用电力来萃取物质\n每次萃取需要消耗\n10Bp电力\生产时间5秒"
STRINGS.NAMES.BULING_RONGLU = "萃取机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU= "用电力来萃取物质\n每次萃取需要消耗10Bp电力"
STRINGS.NAMES.BULING_RADAR = "不灵雷达"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR= "消耗庞大的电力进行一次极大范围的侦查\n需要800Bp的电力才能工作"
STRINGS.NAMES.BULING_DIANLIFU = "电动斧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANLIFU= "这种电力工具效率还不算坏"
STRINGS.NAMES.BULING_JIANDAO = "合金剪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANDAO= "这种工具耐久还不算坏"
STRINGS.NAMES.BULING_DIANDONGGAO = "电动镐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDONGGAO= "这种电力工具效率还不算坏"
STRINGS.NAMES.BULING_CROPBOX = "电动收割机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX= "用于收割周围的植物\n需要50Bp的电力才能启动一次"
STRINGS.NAMES.BULING_DIANDENG = "电灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG= "我说，要有光\n耗电1Bp/s"
STRINGS.NAMES.BULING_LAMP = "太阳能路灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LAMP= "绝佳的照明设备\n白天自动关闭\n夜间自动开启"
STRINGS.NAMES.BULING_CHEMISTRYTABLE = "化学台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEMISTRYTABLE= "用来制作一些化学试剂"
STRINGS.NAMES.BULING_SHENGCUN = "生存发电机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN= "燃烧寻常可见的燃料来发电，发电效率5Bp/5s\n补充一次燃料能用很久"
STRINGS.NAMES.BULING_REPAIR_BOX = "机甲修理器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_REPAIR_BOX= "可以修复范围内的载具\n用炮塔来维修\n我可没想过这个"
STRINGS.NAMES.BULING_PAOTAI = "简易炮塔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI= "只有这些材料和工具我只能做到这种地步了\n没有电力时它将停止工作"
STRINGS.NAMES.BULING_SOLARENERGY = "太阳能电池板MK1"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY= "理所当然的发电机\n发电效率会随着天气变化而变化\n最佳环境时产电2Bp/s"
STRINGS.NAMES.BULING_HUOSAI = "活塞引擎"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI= "人力发电机\n发电效率全看人力\n最佳情况产电2Bp/s"
STRINGS.NAMES.BULING_ZHONGJIQI = "电力中继器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI= "用来储存并将电力供给其他机器"
STRINGS.NAMES.BULING_ZHONGJIQI_GAOYA = "高压中继器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_GAOYA= "存储传输电力\n效率是原来的5倍"
STRINGS.NAMES.BULING_FENSUI = "粉碎机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENSUI= "用来销毁物品\n虽然需要电力支持\n但是工作并不耗电"
STRINGS.NAMES.BULING_SEEDBOX = "作物管家"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX= "让作物冬天生长夏天不枯\n稍微增加作物生长速度\n耗电1Bp/s"
STRINGS.NAMES.BULING_WEAPONCHEST = "机械加工炉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST= "科技不是第一战斗力\n每次工作耗电50Bp"
STRINGS.NAMES.BULING_CHONGDIANQI = "充电器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI= "用来给我的电力工具充电"
STRINGS.NAMES.BULING_PLANTTABLE = "植物改良桌"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE= "用来进行对植物的改良，因为没有使用电力，所以改造的程度有限"
STRINGS.NAMES.BULING_DIANDENG_ITEM = "电灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_SHENGCUN_ITEM = "生存发电机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_HUOSAI_ITEM = "人力发电机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_SOLARENERGY_ITEM = "太阳能发电机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_ZHONGJIQI_ITEM = "电力中继器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_ZHONGJIQI_GAOYA_ITEM = "高压中继器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_GAOYA_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_SEEDBOX_ITEM = "作物管家"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_PAOTAI_ITEM = "简易炮台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_RADAR_ITEMFN = "不灵雷达"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR_ITEMFN= "安置在地上使用"
STRINGS.NAMES.BULING_CROPBOX_ITEM = "电动收割机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_COOKTABLE_ITEM = "料理台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOKTABLE_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_WEAPONCHEST_ITEM = "机械加工炉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_CHONGDIANQI_ITEM = "充电器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_PLANTTABLE_ITEM = "植物改良桌"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_DIANXIANGAN_ITEM = "电力输送端"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANXIANGAN_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_WAKUANG = "简易挖矿机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG= "可以从地下挖矿"
STRINGS.NAMES.BULING_WAKUANG_ITEM = "简易挖矿机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_PILIANGHECHENG_ITEM = "批量合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PILIANGHECHENG_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_ZHONGJIQI_GAOYA_ITEM = "高压中继器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_GAOYA_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_INFINITEBOX_ITEM = "次元存储装置"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_INFINITEBOX_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_TONGXUNTAI_ITEM = "通讯台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TONGXUNTAI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_PICKAXE_WEAPON = "铔金镐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PICKAXE_WEAPON= "用铔晶强化的电动镐\n可以使用灵能冲刺\n灵能冲击,灵能爆破\n右键释放灵能技能\n攻击叠加灵压强化能力"
STRINGS.NAMES.BULING_SHEARS_WEAPON = "铔金剪刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHEARS_WEAPON= "用铔晶强化的合金剪\n可以使用灵能跃迁\n同感莲华,完美莲华\n右键释放灵能技能\n攻击叠加灵压强化能力"
STRINGS.NAMES.BULING_AXE_WEAPON = "铔金斧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_AXE_WEAPON= "用铔晶强化的电动镐\n可以使用灵能震荡\n灵能冲锋,灵能践踏\n右键释放灵能技能\n攻击叠加灵压强化能力"
STRINGS.NAMES.BULING_JIXIEBI_ITEM = "机械臂传送带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIXIEBI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_CHUANSONGDAI_ITEM = "传送带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHUANSONGDAI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_SHUIPEI_ITEM = "土培箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHUIPEI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_CHEST_MINI_ITEM = "物流箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEST_MINI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_ZIDONGHECHENG_ITEM = "自动合成台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZIDONGHECHENG_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_FENGRENJI_ITEM = "缝纫机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENGRENJI_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_REPAIR_BOX_ITEM = "机甲修理器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_REPAIR_BOX_ITEM= "安置在地上使用"
STRINGS.NAMES.BULING_FENSUI_ITEM = "粉碎机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENSUI_ITEM= "安置在地上使用"
--种子&植株
STRINGS.NAMES.BULING_PLANT_ROCK = "岩石植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ROCK= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_MARBLE = "大理石植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_MARBLE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_NITRE = "硝石植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_NITRE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_GOLD = "黄金植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_GOLD= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_OBSIDIAN = "黑曜石植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_OBSIDIAN= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_IRON = "铁矿植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_IRON= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_THULECITE = "铥矿植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_THULECITE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_PLANT_FLINT = "燧石植株"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_FLINT= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_CAIYUAN_DUOFENG = "多风菜园"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAIYUAN_DUOFENG= "可以一次获取多种作物"
STRINGS.NAMES.BULING_CAIYUAN_PINJI = "贫瘠菜园"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAIYUAN_PINJI= "可以一次获取多种作物"
STRINGS.NAMES.BULING_CAIYUAN_REDAI = "热带菜园"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAIYUAN_REDAI= "可以一次获取多种作物"
STRINGS.NAMES.BULING_CAIYUAN_SHIRUN = "湿润菜园"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAIYUAN_SHIRUN= "可以一次获取多种作物"
STRINGS.NAMES.BULING_CAIYUAN_YINBI = "荫蔽菜园"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAIYUAN_YINBI= "可以一次获取多种作物"
STRINGS.NAMES.BULING_PLANT_WHEAT = "小麦"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_WHEAT= "非常好的粮食来源\n不过闪耀世界的麦子。。不长这样啊"
STRINGS.NAMES.BULING_SEED_ROCK = "岩石种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ROCK= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_MARBLE = "大理石种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_MARBLE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_NITRE = "硝石种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_NITRE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_GOLD = "黄金种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_GOLD= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_OBSIDIAN = "十胜石种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_OBSIDIAN= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_FLINT = "燧石种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_FLINT= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_IRON = "铁矿种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_IRON= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_THULECITE = "铥矿种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_THULECITE= "可以吸收土地中的矿物质"
STRINGS.NAMES.BULING_SEED_WHEAT = "麦穗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_WHEAT= "非常好的粮食来源"
STRINGS.NAMES.BULING_SEED_DUOFENG = "多风菜园种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_DUOFENG= "种下后可以收获多风作物包\n包含胡萝卜，南瓜，茄子\n石榴，玉米，浆果\n随机抽取4个"
STRINGS.NAMES.BULING_SEED_REDAI = "热带菜园种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_REDAI= "种下后可以收获热带作物包\n包含椰子，香蕉，西瓜\n火龙果，榴莲\n随机抽取4个"
STRINGS.NAMES.BULING_SEED_SHIRUN = "湿润菜园种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_SHIRUN= "种下后可以收获湿润作物包\n包含芦荟，芦笋，荨麻\n小萝卜，芦苇\n随机抽取4个"
STRINGS.NAMES.BULING_SEED_YINBI = "荫蔽菜园种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_YINBI= "种下后可以收获荫蔽作物包\n包含红蘑菇，绿蘑菇\n蓝蘑菇，豆虫，糖蛞蝓\n随机抽取4个"
STRINGS.NAMES.BULING_SEED_PINJI = "贫瘠菜园种子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_PINJI= "种下后可以收获贫瘠作物包\n包含仙人掌，仙人掌花\n块茎，开花块茎，番薯\n随机抽取4个"
STRINGS.NAMES.BULING_MANURE = "钾硝肥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE= "不错的廉价肥料"
STRINGS.NAMES.BULING_MANURE_8 = "钾硝肥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE_8= "不错的廉价肥料"
STRINGS.NAMES.BULING_CLOTHE_1 = "黑色衬衫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_1= "提供120防暑\n虽然大夏天应该穿浅色"
STRINGS.NAMES.BULING_CLOTHE_2 = "棕色毛衣"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_2= "提供120保暖\n这下暖和多了"
STRINGS.NAMES.BULING_CLOTHE_3 = "绅士礼服"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_3= "提供精神回复\n虽然不如贝雷帽保暖\n但是也能让我精神"
STRINGS.NAMES.BULING_CLOTHE_4 = "黄色运动服"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_4= "提供速度\n穿上它我能跑更快"
STRINGS.NAMES.BULING_CLOTHE_5 = "蓝色运动衫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_5= "提供120防暑\n提供120保暖\n冬夏都能穿"
STRINGS.NAMES.BULING_CLOTHE_6 = "透气格子衫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_6= "防风防毒气\n码农衫。。。\n恐怕作者还在996"
STRINGS.NAMES.BULING_CLOTHE_7 = "橙色大衣"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_7= "提供240保暖\n有羽绒服就好了"
STRINGS.NAMES.BULING_CLOTHE_8 = "怪物大衣"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_8= "会被当成怪物\n用来混进怪物堆里\n提供120保暖"
STRINGS.NAMES.BULING_CLOTHE_9 = "太阳能衬衫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CLOTHE_9= "给身上的电器供电\n这真的不是病号服？"
STRINGS.NAMES.BULING_TROUSER_1 = "普通裤子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_1= "提供4天的耐久"
STRINGS.NAMES.BULING_TROUSER_2 = "黑色裤袜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_2= "提供7天的耐久"
STRINGS.NAMES.BULING_TROUSER_3 = "蓝格子裤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_3= "提供10天的耐久"
STRINGS.NAMES.BULING_TROUSER_4 = "条纹裤子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_4= "提供13天的耐久"
STRINGS.NAMES.BULING_TROUSER_5 = "黑色牛仔裤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_5= "提供16天的耐久"
STRINGS.NAMES.BULING_TROUSER_6 = "结实裤子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TROUSER_6= "提供19天的耐久"
STRINGS.NAMES.BULINGBULING_SIKUSHUI = "沉沦的死库水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULINGBULING_SIKUSHUI= "20天的耐久\n提供240防暑,防雾\n100%防水和绝缘\n夏日最常见的身影\n矿机几率出石油"
STRINGS.NAMES.BULING_EVENINGROBE = "绯红的梦境"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_EVENINGROBE= "1350耐久，80护甲\n穿戴时死亡后复活\n并销毁这个装备\n踏入永恒,如梦似幻"
STRINGS.NAMES.BULING_DENIM = "园丁之影"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DENIM= "暂无效果"
STRINGS.NAMES.BULING_CARDINAL = "征服毁灭的贤者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CARDINAL= "2天耐久\n被猪镇市民当作贵族\n召唤友善的合金巨兽\n映照在毁灭季挺立的身影"
STRINGS.NAMES.BULING_DANCER_DRAGON = "格斗者的盛怒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DANCER_DRAGON= "2天耐久\n允许使用滑铲\n空手攻击造成50伤害\n百般武艺\n此乃电子CQC！"
STRINGS.NAMES.BULING_CHRISTMAS = "圣诞之心"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHRISTMAS= "20天耐久\n提供480保暖和发光\n较高精神回复\n梦想征服冰雪的勇士"
--料理
STRINGS.NAMES.BULING_COOKTABLE = "料理台"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOKTABLE= "用来制作料理\n可以做到完全除菌\n但是好像没什么用"
STRINGS.NAMES.BULING_COOK_KAOPAN = "烤盘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_KAOPAN= "用来制作烤制料理"
STRINGS.NAMES.BULING_COOK_GUO = "烹煮锅"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_GUO= "用来制作锅料理"
STRINGS.NAMES.BULING_CREAM = "奶油慕斯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CREAM= "不一定要用奶制品\n将蛋,奶类食材给予菜刀"
STRINGS.NAMES.BULING_COOK_CAIDAO = "菜刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_CAIDAO= "用来制作菜刀料理"
STRINGS.NAMES.BULING_COOK_KAO = "烤制料理模块"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_KAO= "用来制作烤制料理"
STRINGS.NAMES.BULING_COOK_ZHENG = "锅料理模块"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_ZHENG= "用来制作锅料理"
STRINGS.NAMES.BULING_BREAD = "面包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BREAD= "烤制料理，食材\n非常普通的面包\n味道不是太好"
STRINGS.NAMES.BULING_XIFAN = "稀饭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIFAN= "锅料理，食材\n所谓的面稀饭\n填不饱肚子"
STRINGS.NAMES.BULING_HONGGUZHOU = "红菇粥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HONGGUZHOU= "锅料理\n稀饭里加了些蘑菇\n毒素解除：可以解毒"
STRINGS.NAMES.BULING_LANGUZHOU = "蓝菇粥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LANGUZHOU= "锅料理\n稀饭里加了些蘑菇\n健康:持续90秒\n健康:缓慢恢复生命"
STRINGS.NAMES.BULING_LVGUZHOU = "绿菇粥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LVGUZHOU= "锅料理\n味道不错\n美味：持续90秒\n美味:少量恢复精神"
STRINGS.NAMES.BULING_SANGUBAO = "蘑菇天国"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANGUBAO= "锅料理\n蘑王弗兰克：持续120秒\n蘑王弗兰克：三维均缓慢恢复"
STRINGS.NAMES.BULING_AOLIAO = "奥利奥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_AOLIAO= "烤制料理\n释放咖啡因\n咖啡因:持续300秒\n咖啡因:增加移速"
STRINGS.NAMES.BULING_LUOBUBAO = "萝卜煲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LUOBUBAO= "锅料理\n胡萝卜素：持续120秒\n胡萝卜素：夜视"
STRINGS.NAMES.BULING_JIANGGUOMUSI = "浆果慕斯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANGGUOMUSI= "烤制料理\n美味:持续60秒\n美味:少量恢复精神"
STRINGS.NAMES.BULING_BAOJIANGDANGAO = "爆浆蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BAOJIANGDANGAO= "烤制料理\n甜美浆汁\n开胃:持续250秒\n开胃:缓慢恢复饱食"
STRINGS.NAMES.BULING_BINGKAXIANBING = "宾卡馅饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BINGKAXIANBING= "烤制料理\n香酥可口\n提神:持续100秒\n提神:恢复精神"
STRINGS.NAMES.BULING_MAPODOUFU = "麻婆豆腐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MAPODOUFU= "锅料理\n为啥豆虫能做成豆腐呢\n炽热:持续60秒\n炽热:攻击时造成额外伤害"
STRINGS.NAMES.BULING_KAOLENGMIAN = "烤冷面"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAOLENGMIAN= "烤制·菜刀料理\n再来点辣酱\n开胃：持续60秒\n开胃:缓慢恢复饱食"
STRINGS.NAMES.BULING_SANMINGZHI = "仙人掌三明治"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANMINGZHI= "菜刀料理\n超提神:持续30秒\n超提神:恢复大量精神"
STRINGS.NAMES.BULING_JIANBINGGUOZI = "煎饼果子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANBINGGUOZI= "烤制·菜刀料理\n只能用叶肉做火腿了\n健康:持续90秒\n健康:缓慢恢复生命"
STRINGS.NAMES.BULING_QIANCENGBING = "千层饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIANCENGBING= "烤制料理\n超饱腹:持续30秒\n超饱腹:恢复大量饱食"
STRINGS.NAMES.BULING_XIANGCAOBUDING = "香草布丁"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIANGCAOBUDING= "锅料理\n超美味:持续30秒\n超美味:恢复大量生命"
STRINGS.NAMES.BULING_KAODIGUA = "烤地瓜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAODIGUA= "烤制料理\n冬天穷人之友\n总之果腹没问题"
STRINGS.NAMES.BULING_TIANMISHALA = "甜蜜沙拉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TIANMISHALA= "菜刀料理\n花香:持续60秒\n花香:偶尔吸引点蝴蝶"
STRINGS.NAMES.BULING_XIANGJIAOXIANBING = "香蕉煎饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIANGJIAOXIANBING= "烤制料理\n香蕉味:持续60秒\n香蕉味:被猴群当成猴王"
STRINGS.NAMES.BULING_XIGUAZHI = "西瓜汁"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIGUAZHI= "菜刀料理\n美味:持续60秒\n美味:少量恢复精神"
STRINGS.NAMES.BULING_SUROUDACAN = "素肉大餐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SUROUDACAN= "烤制料理\n饱腹:持续60秒\n饱腹:恢复饱食"
STRINGS.NAMES.BULING_FANGXINGJIAOTANG = "方形焦糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FANGXINGJIAOTANG= "烤制料理\n比太妃糖还要甜\n美味:持续240秒\n美味:少量恢复精神"
STRINGS.NAMES.BULING_FANSHUJIANBING = "番薯煎饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FANSHUJIANBING= "烤制料理\n饱腹:持续30秒\n饱腹:恢复饱食"
STRINGS.NAMES.BULING_FANSHUNI = "番薯泥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FANSHUNI= "锅料理\n简单的将番薯\n捣碎并蒸熟而已"
STRINGS.NAMES.BULING_FANSHUZHOU = "番薯粥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FANSHUZHOU= "锅料理\n开胃:持续45秒\n开胃:缓慢恢复饱食"
STRINGS.NAMES.BULING_FENGMIBUDING = "蜂蜜布丁"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENGMIBUDING= "烤制料理\n谷物香:持续180秒\n谷物香:容易吸引鸟类"
STRINGS.NAMES.BULING_FENGMIMIANBAO = "蜂蜜面包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FENGMIMIANBAO= "菜刀料理\n花香:持续60秒\n花香:容易吸引蝴蝶"
STRINGS.NAMES.BULING_GUODONGJUAN = "果冻卷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUODONGJUAN= "烤制料理\n养生:持续60秒\n养生:恢复生命"
STRINGS.NAMES.BULING_GUOJIANGTONGXINFEN = "果酱通心粉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GUOJIANGTONGXINFEN= "锅料理\n美味:持续180秒\n美味:少量回精神"
STRINGS.NAMES.BULING_HONGGUMIANBAO = "红菇面包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HONGGUMIANBAO= "料理\n养生:持续60秒\n养生:恢复生命"
STRINGS.NAMES.BULING_HULUOBOTANG = "胡萝卜汤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HULUOBOTANG= "锅料理\n胡萝卜素:持续180秒\n胡萝卜素:夜视"
STRINGS.NAMES.BULING_JIANGGUODANGAO = "浆果蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANGGUODANGAO= "烤制料理\n提神:持续120秒\n提神:恢复精神"
STRINGS.NAMES.BULING_JIANGGUOSANMINGZHI = "浆果三明治"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANGGUOSANMINGZHI= "菜刀料理\n饱腹:持续120秒\n饱腹:恢复饱食"
STRINGS.NAMES.BULING_KAFEITANG = "咖啡糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAFEITANG= "烤制料理\n咖啡因:持续480秒\n咖啡因:增加移速"
STRINGS.NAMES.BULING_LUOBODANGAO = "萝卜蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LUOBODANGAO= "烤制料理\n胡萝卜素:持续120秒\n胡萝卜素:夜视"
STRINGS.NAMES.BULING_LUOBOGAO = "萝卜糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LUOBOGAO= "烤制料理\n胡萝卜素:持续120秒\n胡萝卜素:夜视"
STRINGS.NAMES.BULING_MIANBAOPIAN = "面包片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MIANBAOPIAN= "菜刀料理\n饱腹:持续60秒\n饱腹:恢复饱食"
STRINGS.NAMES.BULING_MOGUHANBAO = "蘑菇汉堡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MOGUHANBAO= "菜刀料理\n蘑王弗兰克:持续180秒\n蘑王弗兰克:三维均缓慢恢复"
STRINGS.NAMES.BULING_MOGUTANG = "蘑菇汤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MOGUTANG= "锅料理\n蘑王弗兰克:持续240秒\n蘑王弗兰克:三维均缓慢恢复"
STRINGS.NAMES.BULING_NAILAOTONGXINFEN = "奶酪通心粉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_NAILAOTONGXINFEN= "锅料理\n养生:持续100秒\n养生:恢复生命"
STRINGS.NAMES.BULING_PISA = "披萨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PISA= "烤制料理\n皇室气息:持续240秒\n皇室气息:会被猪镇\n居民当成皇族"
STRINGS.NAMES.BULING_QIAOKELIPAI = "巧克力派"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIAOKELIPAI= "烤制料理\n超提神:持续100秒\n超提神:恢复大量精神"
STRINGS.NAMES.BULING_QIAOKELIXIANBING = "巧克力馅饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIAOKELIXIANBING= "烤制料理\n谷物香:持续240秒\n谷物香:容易吸引鸟类"
STRINGS.NAMES.BULING_QIEHESHUTIAO = "茄盒薯条"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIEHESHUTIAO= "烤制料理\n超美味:持续80秒\n超美味:恢复大量生命"
STRINGS.NAMES.BULING_SHUCAISHALA = "蔬菜沙拉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHUCAISHALA= "锅料理\n超提神:持续4秒\n超提神:恢复大量精神"
STRINGS.NAMES.BULING_SHUCAISUI = "蔬菜碎"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHUCAISUI= "将素菜瞎切一通\n将生的素菜给予菜刀\n有几率获得2个"
STRINGS.NAMES.BULING_SUANRONGGUHE = "素菇盒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SUANRONGGUHE= "烤制料理\n蘑王弗兰克:持续90秒\n蘑王弗兰克:三维均缓慢恢复"
STRINGS.NAMES.BULING_SUANRONGMIANBAO = "蔬菜面包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SUANRONGMIANBAO= "菜刀料理\n健康:持续60秒\n健康:缓慢恢复生命"
STRINGS.NAMES.BULING_TIANSHUNI = "甜薯泥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_TIANSHUNI= "锅料理\n健康:持续120秒\n健康:缓慢恢复生命"
STRINGS.NAMES.BULING_ZHALUOBOWANZI = "炸萝卜丸子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHALUOBOWANZI= "烤制料理\n胡萝卜素:持续45秒\n胡萝卜素:夜视"
STRINGS.NAMES.BULING_ZHAWANZI = "炸丸子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHAWANZI= "烤制料理\n素菜裹上面粉炸\n很普通的菜品"


--配方
STRINGS.BUINGKEJI = "不灵科技"
STRINGS.BULING_YANJIU = "研究科技"
STRINGS.RECIPE_DESC.BULING_WEAPONCHEST_ITEM="制作高级机器"
STRINGS.RECIPE_DESC.BULING_MANUAL="开发新点子的工作站"
STRINGS.RECIPE_DESC.BULING_CAVE_TOOL="把脆弱的岩层\n固定成洞穴"
STRINGS.RECIPE_DESC.BULING_FADIANJI_HUOLI="进入电气时代"
STRINGS.RECIPE_DESC.BULING_ZHONGJIQI="无线电池"
STRINGS.RECIPE_DESC.BULING_WAKUANG_ITEM="更多的矿物"
STRINGS.RECIPE_DESC.BULING_LINGJIAN="加工材料的车床"
STRINGS.RECIPE_DESC.BULING_KUANGJIA="做机器的必备品"
STRINGS.RECIPE_DESC.BULING_PAOTAI="基础守卫"
STRINGS.RECIPE_DESC.BULING_YAJIN="从黑曜石中提取铔金"
STRINGS.RECIPE_DESC.BULING_BOOK_YAJIN="一份研究资料"
STRINGS.RECIPE_DESC.BULING_BOOK_TONGXUNTAI="一份研究资料"
STRINGS.RECIPE_DESC.BULING_TONGXUNTAI_ITEM="终于可以对外通信了"
STRINGS.RECIPE_DESC.BULING_YANJIUTAI="用来进行模拟试验\n从而获得资料"
STRINGS.RECIPE_DESC.BULING_COOKTABLE_ITEM="无菌烹饪环境\n料理不会腐败"
STRINGS.RECIPE_DESC.BULING_FENGRENJI_ITEM="啊哈，新衣服"
--3x3配方
STRINGS.BULING_ZHONGZIDING_SHUOMING = "很环保的金属\n用量会很大\n可以批量种植\n我大学毕业时研究的"
STRINGS.BULING_SEED_ZHONGZIDING_SHUOMING = "1天就能成熟\n可反复收获\n应该大量种植"
STRINGS.BULING_RONGLU_SHUOMING = "用于萃取材料\n每次萃取需要10Bp电力\n可储存200Bp电力"
STRINGS.BULING_ZHONGJIQI_SHUOMING = "最重要的机器之一\n用于储存发电机输出的电力\n并将储存的电力供给其他机器\n自身也常用于机器合成"
STRINGS.BULING_SHENGCUN_SHUOMING = "燃烧寻常可见的燃料来发电\n发电效率5Bp/5s\n补充一次燃料能用很久"
STRINGS.BULING_PAOTAI_SHUOMING = "攻击力15\n生命50\n脆弱的炮塔\n每次耗电5Bp"
STRINGS.BULING_RADAR_SHUOMING = "需要800Bp的电力才能工作\n探测一次全世界\n一段时间内玩家的地图全开\n退出游戏后重新变黑"
STRINGS.BULING_CROPBOX_SHUOMING = "可以快速采集周围的作物\n需要50Bp的电力采集一次"
STRINGS.BULING_DIANDENG_SHUOMING = "可以发出普通的光\n耗电5Bp/5s"
STRINGS.BULING_WEAPONCHEST_SHUOMING = "生产实用装备\n每次工作耗电50Bp"
STRINGS.BULING_SEEDBOX_SHUOMING = "可以照顾作物\n让作物冬天能够继续生长\n夏天不会枯萎"
STRINGS.BULING_SOLARENERGY_SHUOMING = "利用阳光发电\n最大产电10Bp/5s"
STRINGS.BULING_TOOL_SHUOMING = "一个很优秀的工具\n而且可以充电"
STRINGS.GEARS_SHUOMING = "这种零件永远不会过时"
STRINGS.BULING_CHONGDIANQI_SHUOMING = "用来给电力工具充电"
STRINGS.BULING_BANSHOU_SHUOMING = "轻松搬运机器"
STRINGS.BULING_PLANTTABLE_SHUOMING = "改良植物种子"
STRINGS.BULING_CHEST_SHUOMING = "大箱子"
STRINGS.BULING_SEED_SHUOMING = "通过基因改造\n来更好的获取资源"
STRINGS.ROCK_SHUOMING = "这石头一点不圆润\n盘它！"
STRINGS.SEEDS_SHUOMING = "让种子重新获得随机性"
STRINGS.BULING_GOLD_DUST = "充分提取其中的黄金"
STRINGS.BULING_CLOTHES_PEIFANG = "上方放上衣\n下方放裤子\n缝合出成衣\n上衣提供功能\n裤子提供耐久"

--杂项
STRINGS.BULING_CLOTHES = "缝合衣服"
STRINGS.BULINGYANJIU = "研究"
STRINGS.DUANKAILIANJIE = "断开连接"
STRINGS.CAVEBUILD = "这里的岩层还很厚\n我需要多挖些矿以破碎岩层"
STRINGS.YUNSHI = "已捕捉到目标陨石"
STRINGS.BULINGYANJIUSHIBAI = "我要在吃饱而且精神充足的情况下才能研究"
STRINGS.CAILIAOBUZU = "材料不足"
STRINGS.POWER = "电力"
STRINGS.FUEL = "燃料"
STRINGS.PROGRESS = "生产进度"
STRINGS.BULINGITEM = "目标物品"
STRINGS.BULINGTIME = "剩余时间"
STRINGS.BULING_BWNG = "电力不足"
STRINGS.BULING_BWNG2 = "\n需要50Bp电力才能工作一次"
STRINGS.BULING_STSTEM = "打开终端"
STRINGS.BULING_ENZYME = "抽取"
STRINGS.BULING_LEIDA = "我从雷达上下载好临时的地图资料了"
STRINGS.DIXI_LOW = "袭击者已经到来，即将进行攻击"
STRINGS.DIXI_LONG = "袭击者已经到来，他们稍做准备后进行攻击"
STRINGS.XINGZHICAI = "一些星之彩亚种来到了这个地区"
STRINGS.ERTONGJIE = "儿童节快乐"
STRINGS.DAODANHONGZHA = "轰炸目标"
STRINGS.COLONIES = "殖民地"
STRINGS.SHIPTEXT = "商船"
STRINGS.BLACKMARKET = "邪教黑市"
STRINGS.NOSIGNAL = "无信号"
STRINGS.ELDERTHING = "古老者"
STRINGS.YITH = "伊斯人"
STRINGS.SHAGGAI = "夏盖虫族"
STRINGS.MIGO = "米戈"
STRINGS.BULING_SNOWSKELETON_DEF = "防御模式"
STRINGS.BULING_SNOWSKELETON_ATK = "进攻模式"
STRINGS.BULING_SNOWSKELETON_NEU = "中立模式"
local STRINGS = GLOBAL.STRINGS
STRINGS.UI.WORLDGEN.BLTITLE = "前往外星球"
STRINGS.UI.WORLDGEN.BL_VERBS = {
    "产生",
    "畜牧",
    "浸湿",
    "迭代",
    "暗示",
    "网状化",
    "促进",
    "插入",
    "分配",
    "允许",
    "创造",
    "增殖",
    "灌溉",
    "测量",
}
STRINGS.UI.WORLDGEN.BL_NOUNS = {
    "肉胶",
    "痛苦",
    "月怪",
    "厄尔吉斯水晶",
    "怪物",
    "强烈的绝望感",
    "成桶成桶地战利品",
    "模组功能",
    "班花的胖次",
	"01的节操",
    "糖煎竹子",
    "宵征大佬",
    "吃撑的贝尔",
    "咸鱼干",
    "易汁黛苗",
    "nil",     
}
STRINGS.TASK = [[
	emmmmmmmmmmmm
]]
STRINGS.TASK1 = [[
本教程灵感来源自以下内容：
《我晚上看》《吃完饭再来》
《能用就行了》《咕咕咕咕咕咕咕咕咕咕》
《更新是不可能更新的,这辈子都不可能更新的》
《睡醒了看》《我怎么又睡着了》《明天再说》]]
STRINGS.TASK2 = [[
现在是x年x月x日，终端第5/5次尝试连接飞船数据库
---------------------------------------
连接失败，搜索不到飞船数据库，请在信号良好的地带重试
终端第5/5次尝试连接闪耀世界数据库
---------------------------------------
连接失败，搜索不到闪耀世界数据库，请在信号良好的地带重试
确定闪耀世界中心服务器信号丢失
再次确认，闪耀世界中心服务器信号丢失
终端认为你进入了未开化领域
终端认为完全没有野外生存经验的你会很快死掉
K404航班穿梭机的失事率仅为0.003%
因为虫洞效应而离开闪耀世界范围的
理论机率仅为0.0002%
]]
STRINGS.TASK3 = [[
终端查阅了你的大学论文报告
终端认为你的一些作品能派的上用场
为了获取闪耀世界的救援你需要建立基站
以此和闪耀世界进行联系
为了实现这个目的你需要电力设备
终端找到了你毕业后设计的通讯机蓝图
尽管现在已经被新产品淘汰但是还是能用的
但是你至少得先得到矿产资源
]]
STRINGS.TASK4 = [[
好吧，对的，你以前有过类似的发明
终端查阅了你曾经写过的所有论文
你有设想过一种环保金属，塞德锭SeedSpindle
而且为了通过你的这篇论文。。
你有设计过一套相关的完整产业
希望你没有因为长期混在实验室完全忘掉手工操作
虽然终端也认为那些机械手臂非常好用
总之，终端认为你应该先搞出塞德锭
根据你的论文，塞德锭的核心是少量金属和种子胚胎
]]
STRINGS.TASK5 = [[
任务：通用金属
条件：获得1个塞德锭
说明：连塞德锭都没有你甚至都活不下去！
制作塞德锭的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
任务奖励？别傻了
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK6 = [[
看来你已经走出材料学的第一步了
但是别放松，这才刚刚开始
工业是靠材料堆出来的
仅仅几个塞德锭压根不够塞牙缝
别担心，塞德锭你可是宣城通用性最强的
你有设计过它的种植功能，能够大量生产的
但是在此之前，为了你那可怜的小胃着想
终端建议你最好解决肚子的问题
那么你应该制作出植物改良桌
这东西可以让你制作出诸如小麦之类的现代作物
地里有粮心里不慌，你以前最喜欢这么说了
]]
STRINGS.TASK7 = [[
任务：现代农业
条件：获得1个植物改良桌
说明：连粮食都没有你甚至都活不下去！
制作植物改良桌的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK8 = [[
终端认为你暂时可能饿不死了
大规模种地吧，为何记录的是你自己设计的麦子
终端表示不能理解
你忘了你为了对付大学毕业时设计的这东西有缺点了吗
它无法被移植，一旦被挖掉会变成最原始的种子
你之后设计的杂交植物都有这类缺点
都是因为你太懒，不想改良基因设计图
终端认为你早晚会因为懒癌遭报应的
这次飞船出事导致你开始荒野求生。。。
不过如果你缺少原始种子的话
可以试图挖掉成熟植株来获得种子
使用注射器可以从成熟植株中抽取聚合酶
用聚合酶可以在一定程度上改写种子的基因
]]
STRINGS.TASK9 = [[
你需要将食物进行加工才能食用
为此你需要电力来供应机器加工食物
终端认为你暂时没有足够的材料制作火力发电机
终端找到了你设计的人力发电机蓝图
终端无法理解设计人力发电机的理由
闪耀社会有戴森球供能，无需简陋的发电机
但是这个蓝图至少能救你一命
即便如此，你还需要准备一个电池
电力中继器是个好选择
可以在存储电力的同时为用电器供电
]]
STRINGS.TASK10 = [[
任务：简单电力
条件：获得1个电力中继器
说明：存储电力是理所当然的吧
制作电力中继器的流程：
打开不灵工作台
按照图鉴摆材料后按下按钮
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK11 = [[
现在请试着制造一个简易的电路吧
制造一个发电放在中继器旁
然后供电给中继器以传输电力
发电机只会向离的最近的中继器供电
而中继器会向全部范围内的用电器供电
请控制好电力的传输
当中继器没电时会自动关闭
如果你把机器放置错了地方
试着做个扳手搬运机器吧
]]
STRINGS.TASK12 = [[
如果你已经完成最基础的电路了
请制造1个萃取器并接入电路
萃取器可以精加工物品
或者提取物品中的元素
试着用萃取器萃取塞德锭吧
]]
STRINGS.TASK13 = [[
任务：硅晶体
条件：获得1个塞德玻璃
说明：天知道这是啥原理
制作塞德玻璃的流程：
打开不灵工作台制造萃取器
按照图鉴摆材料后按下按钮
将萃取器接入电路并充电至少20Bp
放入1个塞德锭按下按钮萃取
{请将目标物品带在身上让终端检查}
]]
STRINGS.TASK14 = [[
塞德玻璃可以用在很多地方
它导电，坚硬，能够传输电磁信号
哦，是的，也许你能用它制造通讯机
不过据终端查阅你的档案。。。
你确实没学过相关专业来着
终端很苦恼，你太偏科了
不过幸好你还擅长撰写Ai
终端建议你拼凑一台电脑ai
用模拟实验来研究相关技术
这会消耗大量的时间和电力
但是能够学习到新的技术
本机这就将你之前的文档调出来
【你学会了制作研究台】
]]
STRINGS.TASK15 = [[
模拟实验可能会消耗很多时间
终端建议多造一些电脑来模拟
之后你可以试图学习其他技术
眼下还是先研究出通讯台吧
如果能联络到附近的飞船
就能早早离开这里了
总之先进行研究吧
不过当地可以找到的通讯材料并不多
终端建议你将本机作为通讯台的AI来使用
【你学会了研究通讯技术】
]]
STRINGS.TASK16 = [[
任务：对外交流
条件：获得1个通讯台
说明：反正肯定回不去（bushi）
制作1个研究台，并进行研究
获得一定量的研究点数
制作研究通讯技术
学会制作通讯台后制作通讯台
由于通讯台材料包含终端
该任务无需提交
注意，过快推进主线会有负面事件
请先以攀科技为主
]]
STRINGS.TASK17 = [[
运行正常，你制作的通讯台应该可以正常工作
不过很遗憾的是终端并不能搜索到你以外的信号
终端认为你所在的地区没有其他人存在
不过终端发现了你隐藏起来的文档，也许这会对你有所帮助
]]
STRINGS.TASK18 = [[
"宇宙似乎不可避免的在向前进
这一趋势无法逆转。。。。。。
但是如果付出足够的代价
现在这一切都可以颠覆"
]]
STRINGS.TASK19 = [[
"当时间驳论开始纠缠之时
一个难以形容的意识开始渐渐苏醒
它渴望着，索求着。。。。。。
如果我能够让自己同这个意识同调，或许可以摸到那道大门"
]]
STRINGS.TASK20 = [[
"思想是世界的映射，也是微型世界
即使不能揭示思想的本质
也能将意识磨炼成最伟大的工具"
【你学会了研究提取铔晶】
]]
STRINGS.TASK21 = [[
终端查询了离线的闪耀世界法典
终端认为这篇文档似乎涉及到了灵能，灵能研究是严重违反科技法的行为
这是违反闪耀世界法律的，终端决定。。。
【你强行修改了AI的逻辑】
]]
STRINGS.TASK22 = [[
警告，AI内核禁止私人进行更改
这次修改将向闪耀世界数据库发送报告
警告，未联网，请稍后重试
警告，未联网，请稍后重试
]]
STRINGS.TASK23 = [[
重启中————————————————————————
---------------------------------------
连接失败，搜索不到闪耀世界数据库，请在信号良好的地带重试
确定闪耀世界中心服务器信号丢失
]]
STRINGS.TASK24 = [[
再次确认，闪耀世界中心服务器信号丢失
终端查询之前的记录，查询完毕，本机开始进行信号搜索
警告！发现登录在案的非法星际海盗信号！终端的信号被拦截了！
【袭击开放，现在开始会有星际海盗来袭击你了】
]]
STRINGS.TASK25 = [[
这可真是糟糕。。。不过终端认为这并不是个坏事
这至少说明你所在的星域还是有其他人活动的
是的，终端肯定你的想法，想办法俘虏一艘海盗飞船很有必要
不过终端觉得你得先制造出足以伤到星际飞船的武器出来
]]
STRINGS.TASK26 = [[
任务：更大火力
条件：获得5个机器核心
说明：为了制造更为强大的武器，需要更多的精密材料
摧毁破损的降落仓有几率掉落机器核心，或者你自己制作
]]
STRINGS.TASK27 = [[
来自闪耀世界的高级机器核心是不可多得的稀有物资
]]
-----------------------------------------------------------------
STRINGS.ERROR_COMMUNICATION = [[
终端在尝试新的联络————————————
链接失败,没有搜索到相关信号
]]










if GetModConfigData("languages") == 2 then
	STRINGS.CHARACTER_TITLES.bulingbuling = "Ms. Buling"
	STRINGS.CHARACTER_NAMES.bulingbuling = "BulingBuling"
	STRINGS.CHARACTER_DESCRIPTIONS.bulingbuling = "*Suffers from insomnia and stomach issues\n*Is way too weak to brandish a weapon\n*Feels gazed by an unknown existence"
	STRINGS.CHARACTER_QUOTES.bulingbuling = "\"Technologies are more than the primary combat forces.\""
	STRINGS.CHARACTERS.BULINGBULING = require "speech_bulingbuling"
	--物品
	STRINGS.NAMES.BULING_GLOMLING = "Gloomy Aircraft"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLOMLING= "Not too many essential modules are loaded except mobile modules, given the limitations in materials."
	STRINGS.NAMES.BULING_CAVE_TOOL = "Excavator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAVE_TOOL= "It takes the miner at least ten times of mining to clear out a whole cave."
	STRINGS.NAMES.BULING_CAVE_ENTRANCE = "Cave Entrance"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CAVE_ENTRANCE= "Now I'm reduced to primitive style of living."
	STRINGS.NAMES.BULING_FLOUR = "Flour"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_FLOUR= "What comes out of the extractor."
	STRINGS.NAMES.BULING_SYSTEM = "Aircraft Terminal"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SYSTEM= "It'll tell me what to do."
	STRINGS.NAMES.BULING_PLANT_ZHONGZIDING = "SEED Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ZHONGZIDING= "Underground minerals go into it, and SEED ingots come out of it."
	STRINGS.NAMES.BULING_CHEST = "Alloy Chest"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHEST= "Secure and solid."
	STRINGS.NAMES.BULING_BANSHOU = "Buling's Wrench"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BANSHOU= "For shipping machines."
	STRINGS.NAMES.BULING_MANUAL_ITEM = "Crafting Table"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL_ITEM= "Put it down for crafting."
	STRINGS.NAMES.BULING_MANUAL = "Crafting Table"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "Like the ones in Minecraft!"
	STRINGS.NAMES.BULING_GLASS = "SEED Glass"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_GLASS= "Prepared by extracting SEED ingots.\nBrilliant enough."
	STRINGS.NAMES.BULING_SEED_ZHONGZIDING = "SEED Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ZHONGZIDING= "A reliable source of SEEDs once at full growth."
	STRINGS.NAMES.BULING_MANUAL = "Working Table"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANUAL= "A place to perform technology and craftsmanship."
	STRINGS.NAMES.BULING_ZHONGZIDING = "SEED Ingot"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGZIDING= "Plantable and renewable and eco-friendly\nI think I'm into it."
	STRINGS.NAMES.BULING_RONGLU_ITEM = "Extractor"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU_ITEM= "Just place it on the ground."
	STRINGS.NAMES.BULING_RONGLU = "Extractor"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RONGLU= "A machine for extracting\nWorks at a cost of 10Bp of electricity."
	STRINGS.NAMES.BULING_RADAR = "Buling's Radar"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR= "Extremely consuming but quite effective\nNeed 800Bp's electricity to get it working."
	STRINGS.NAMES.BULING_DIANLIFU = "Electric Axe"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANLIFU= "Not too bad efficiency for an electric tool."
	STRINGS.NAMES.BULING_JIANDAO = "Alloy Scissors"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANDAO= "Quite durable."
	STRINGS.NAMES.BULING_DIANDONGGAO = "Electric Pickaxe"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDONGGAO= "Helped me save my labour, any way."
	STRINGS.NAMES.BULING_CROPBOX = "Harvester"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX= "For harvesting nearby crops\nNeed 50Bp of power to turn it on."
	STRINGS.NAMES.BULING_DIANDENG = "Electric Lamp"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG= "Let there be light.\nAt a cost of 1 Bp/s of power consumption."
	STRINGS.NAMES.BULING_SHENGCUN = "Survival Generator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN= "Use combustables to generate electricity at 5Bp/s\nDoesn't need much fuel."
	STRINGS.NAMES.BULING_PAOTAI = "Defensive Turret"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI= "It's the best I can build with these crude tools and materials.\nIt needs power to attack."
	STRINGS.NAMES.BULING_SOLARENERGY = "Solar Panel MK1"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY= "A reasonable generator\nIts efficiency depends on the weather.\nOutputs 2Bp/s in the best condition."
	STRINGS.NAMES.BULING_HUOSAI = "Piston Engine"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI= "A manual generator\nIts efficiency depends on my physical strength\nGenerates 2Bp/s at most."
	STRINGS.NAMES.BULING_ZHONGJIQI = "Electric Repeater"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI= "It stores electricity and allocate it to other consumers."
	STRINGS.NAMES.BULING_SEEDBOX = "Crops Regulator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX= "Prevents growth halt in winter and withering in summer\nMildly increases growth.\nConsumes 1Bp/s"
	STRINGS.NAMES.BULING_WEAPONCHEST = "Processor Furnace"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST= "Technologies are not primitive combat forces.\nConsumes 5Bp/s"
	STRINGS.NAMES.BULING_CHONGDIANQI = "Recharger"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI= "It powers up my ran-out tools."
	STRINGS.NAMES.BULING_PLANTTABLE = "Botanist's Workbench"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE= "For various reworks on plants."
	STRINGS.NAMES.BULING_DIANDENG_ITEM = "Electric Lamp"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_DIANDENG_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_SHENGCUN_ITEM = "Survival Generator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SHENGCUN_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_HUOSAI_ITEM = "Manual Generator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HUOSAI_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_SOLARENERGY_ITEM = "Solar Panel MK1"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SOLARENERGY_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_ZHONGJIQI_ITEM = "Electric Repeater"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_ZHONGJIQI_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_SEEDBOX_ITEM = "Crops Regulator"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEEDBOX_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_PAOTAI_ITEM = "Defensive Turret"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PAOTAI_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_RADAR_ITEMFN = "Buling's Radar"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_RADAR_ITEMFN= "Place it on the ground for using."
	STRINGS.NAMES.BULING_CROPBOX_ITEM = "Harvester"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CROPBOX_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_WEAPONCHEST_ITEM = "Processor Furnace"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WEAPONCHEST_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_CHONGDIANQI_ITEM = "Recharger"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_CHONGDIANQI_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_PLANTTABLE_ITEM = "Botanist's Workbench"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANTTABLE_ITEM= "Place it on the ground for using."
	STRINGS.NAMES.BULING_WAKUANG = "Electric Miner"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG= "It mines, from underground."
	STRINGS.NAMES.BULING_WAKUANG_ITEM = "Electric Miner"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_WAKUANG_ITEM= "Place it on the ground for using."
	
	--种子&植株
	STRINGS.NAMES.BULING_PLANT_ROCK = "Rock Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_ROCK= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_MARBLE = "Marble Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_MARBLE= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_NITRE = "Nitre Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_NITRE= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_GOLD = "Gold Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_GOLD= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_OBSIDIAN = "Obsidian Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_OBSIDIAN= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_FLINT = "Flint Plant"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_FLINT= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_PLANT_WHEAT = "Weeat"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_PLANT_WHEAT= "A reliable food source.\nIt's peculiar look intrigued me though."
	STRINGS.NAMES.BULING_SEED_ROCK = "Rock Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_ROCK= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_MARBLE = "Marble Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_MARBLE= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_NITRE = "Nitre Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_NITRE= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_GOLD = "Gold Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_GOLD= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_OBSIDIAN = "Obsidian Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_OBSIDIAN= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_FLINT = "Flint Seed"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_FLINT= "It absorbs specific minerals from underground."
	STRINGS.NAMES.BULING_SEED_WHEAT = "Weeat"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SEED_WHEAT= "A reliable food source."
	STRINGS.NAMES.BULING_MANURE = "Compound Fertilizer"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE= "Both cheap and efficient."
	STRINGS.NAMES.BULING_MANURE_8 = "Compound Fertilizer"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MANURE_8= "Both cheap and efficient."
	--料理
	STRINGS.NAMES.BULING_COOKTABLE = "Culinary Table"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOKTABLE= "For satisfying my fragile stomach.\nIt provides a sterile place to cook.\nNot of much use, though."
	STRINGS.NAMES.BULING_COOK_KAO = "Roasting Module"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_KAO= "Roasted food grants me temporary boost on max stats.\nAppetizer: hunger boost.\nStimulant: sanity boost.\nTonic: health boost."
	STRINGS.NAMES.BULING_COOK_GUO = "Braising Module"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_GUO= "I gain regeneration over a period of time from food cooked this way.\nBellyful: hunger regeneration.\nDelicacy: sanity regeneration.\nNutriment: health regeneration."
	STRINGS.NAMES.BULING_COOK_ZHENG = "Steaming Module"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_COOK_ZHENG= "Steamed food has various and unique buffs."
	STRINGS.NAMES.BULING_BREAD = "Bread"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BREAD= "Toasted and warm.\nRather common, both in the look and in the taste."
	STRINGS.NAMES.BULING_XIFAN = "Congee"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIFAN= "Boiled and lite.\nMy stomach won't get by with this."
	STRINGS.NAMES.BULING_HONGGUZHOU = "Redcap Congee"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_HONGGUZHOU= "Boiled and mellow.\nTinted with redcaps.\nAntivenom: as the name implys."
	STRINGS.NAMES.BULING_LANGUZHOU = "Bluecap Congee"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LANGUZHOU= "Boiled and mellow.\nHope this tastes alright.\nNutriment: health regeneration over 60s."
	STRINGS.NAMES.BULING_LVGUZHOU = "Greencap Congee"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LVGUZHOU= "Boiled and mellow.\nNow this a proper meal.\nDelicacy: sanity regeneration over 90s."
	STRINGS.NAMES.BULING_SANGUBAO = "Mushropia"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANGUBAO= "Steamed and fragrant.\nMushrlking: temporary boost on all the three main stats.\nMushrlking: lasts for 120s."
	STRINGS.NAMES.BULING_AOLIAO = "Cocrepe"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_AOLIAO= "Roasted and exhilarating.\nRich in caffeine.\nJust like coffee."
	STRINGS.NAMES.BULING_LUOBUBAO = "Carrotroast"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_LUOBUBAO= "Steamed and sweet.\nCarotene: night vision.\nCarotene: lasts for 60s."
	STRINGS.NAMES.BULING_JIANGGUOMUSI = "Berry Mousse"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANGGUOMUSI= "Hand-made and refreshing.\nDelicacy: sanity regeneration over 30s."
	STRINGS.NAMES.BULING_BAOJIANGDANGAO = "Lava Cake"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BAOJIANGDANGAO= "Roasted and sweet.\nAppetizer: hunger boost lasts for 250s."
	STRINGS.NAMES.BULING_BINGKAXIANBING = "Binka Pie"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_BINGKAXIANBING= "Roasted and crisp.\nStimulant: sanity boost lasts for 200s."
	STRINGS.NAMES.BULING_MAPODOUFU = "Mapo Tofu"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_MAPODOUFU= "Braised and tasty.\nTofu made from bean bugs...\nInflame: deals additional damage with attacks.\nInflame: lasts for 60s."
	STRINGS.NAMES.BULING_KAOLENGMIAN = "Cold Noodles"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAOLENGMIAN= "Roasted and spiced.\nAppetizer: hunger boost lasts for 30s."
	STRINGS.NAMES.BULING_SANMINGZHI = "Cactusandwich"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_SANMINGZHI= "Hand-made and refreshing.\nSuper-delicacy: great sanity regeneration.\nSuper-delicacy: lasts for 10s."
	STRINGS.NAMES.BULING_JIANBINGGUOZI = "Stuffed Pancake"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_JIANBINGGUOZI= "Roasted and nutritious.\nTonic: health boost lasts for 180s."
	STRINGS.NAMES.BULING_QIANCENGBING = "Layered Pancake"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_QIANCENGBING= "Steamed and satisfying.\nSuper-bellyful: great hunger regeneration.\nSuper-bellyful: lasts for 10s."
	STRINGS.NAMES.BULING_XIANGCAOBUDING = "Vanilla Pudding"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_XIANGCAOBUDING= "Steamed and delicious.\nSuper-nutriment: great health regeneration.\nSuper-nutriment: lasts for 10s."
	STRINGS.NAMES.BULING_KAODIGUA = "Baked Sweet Potato"
	STRINGS.CHARACTERS.GENERIC.DESCRIBE.BULING_KAODIGUA= "Roasted and rich in carbohydrates.\nThis is how people survive the winter in the ancient times.."
	--配方
	STRINGS.BUINGKEJI = "Buling's Tech"
	STRINGS.RECIPE_DESC.BULING_WEAPONCHEST_ITEM="Yet to be completed."
	STRINGS.RECIPE_DESC.BULING_MANUAL="A place for innovation."
	STRINGS.RECIPE_DESC.BULING_CAVE_TOOL="Stabilize the strata and build a cave."
	STRINGS.RECIPE_DESC.BULING_FADIANJI_HUOLI="Here we go, into the electric age."
	STRINGS.RECIPE_DESC.BULING_ZHONGJIQI="Wireless battery."
	STRINGS.RECIPE_DESC.BULING_WAKUANG_ITEM="More minerals are avaliable now."
	STRINGS.RECIPE_DESC.BULING_LINGJIAN="A lathe for material processing."
	STRINGS.RECIPE_DESC.BULING_KUANGJIA="Structrually essential for machines."
	STRINGS.RECIPE_DESC.BULING_PAOTAI="Defensively offensive."
	--3x3配方
	STRINGS.BULING_ZHONGZIDING_SHUOMING = "Eco-friendly metal of great yield and consumption.\nOne of my inventions during college days."
	STRINGS.BULING_SEED_ZHONGZIDING_SHUOMING = "It takes only one day to mature or grow back.\nLarge amount of planting is suggested."
	STRINGS.BULING_RONGLU_SHUOMING = "It extracts things at a cost of 10Bp's power supply.\nIt stores 200Bp at most when idle."
	STRINGS.BULING_ZHONGJIQI_SHUOMING = "One of the most vital machines.\nIt acts as an transfer station of electricity."
	STRINGS.BULING_SHENGCUN_SHUOMING = "Use combustables to generate electricity at 5Bp/s.\nDoesn't need much fuel."
	STRINGS.BULING_PAOTAI_SHUOMING = "Damage=15\nHealth=50\nCosts 5Bp each attack."
	STRINGS.BULING_RADAR_SHUOMING = "I'll need 800Bp of power to turn it on.\nIt reveals the whole map, for a period of time."
	STRINGS.BULING_CROPBOX_SHUOMING = "For quick gathering of nearby crops.\nCosts 50Bp for each harvest."
	STRINGS.BULING_DIANDENG_SHUOMING = "It sheds mild light around it.\nConsumes power 1Bp/s"
	STRINGS.BULING_WEAPONCHEST_SHUOMING = "Things made on it don't make me feel any safer.\nCosts 50Bp for each craft."
	STRINGS.BULING_SEEDBOX_SHUOMING = "It is constantly tending to nearby crops,\nprotects them from cold or heat. "
	STRINGS.BULING_SOLARENERGY_SHUOMING = "It converses solar energy into electricity.\nOutputs 2Bp/s in the best condition."
	STRINGS.BULING_TOOL_SHUOMING = "Rechargable and efficient."
	STRINGS.GEARS_SHUOMING = "These won't go outdated that easily."
	STRINGS.BULING_CHONGDIANQI_SHUOMING = "For recharging ran-out tools."
	STRINGS.BULING_BANSHOU_SHUOMING = "For easy shipping of heavy machines."
	STRINGS.BULING_PLANTTABLE_SHUOMING = "Reworked seeds."
	STRINGS.BULING_CHEST_SHUOMING = "A large chest."
	STRINGS.BULING_SEED_SHUOMING = "Yield increased, by genetic modification."
	STRINGS.ROCK_SHUOMING = "Such a rough rock. Let's polish it!"
	STRINGS.SEEDS_SHUOMING = "Randomize these seeds."
	
	--杂项
	STRINGS.BULINGYANJIU = "Research"
	STRINGS.CAVEBUILD = "The strata is too thick.\nMore mining is needed to weaken it."
	STRINGS.YUNSHI = "Target meteorite detected."
	STRINGS.BULINGYANJIUSHIBAI = "I can't research while starving or insane!"
	STRINGS.CAILIAOBUZU = "Not enough material."
	STRINGS.POWER = "Electricity"
	STRINGS.FUEL = "Fuel"
	STRINGS.PROGRESS = "Process"
	STRINGS.BULINGITEM = "Target Item"
	STRINGS.BULINGTIME = "Time Left"
	STRINGS.BULING_BWNG = "Low Power"
	STRINGS.BULING_STSTEM = "Turn On Terminal"
	STRINGS.BULING_LEIDA = "Map data from the radar is loaded."
	STRINGS.DIXI = "Ah, there may be an attack today"
	local STRINGS = GLOBAL.STRINGS
STRINGS.UI.WORLDGEN.BLTITLE = "Embark On Space Exploration"
STRINGS.UI.WORLDGEN.BL_VERBS = {
    "Generating",
    "Herding",
    "Submerging",
    "Iterating",
    "Implying",
    "Reticulating",
    "Facilitating",
    "Inserting",
    "Allocating",
    "Permitting",
    "Creating",
    "Breeding",
    "Irrigating",
    "Measuring",
}
STRINGS.UI.WORLDGEN.BL_NOUNS = {
    "meat jellies",
    "agonies",
    "that Thing",
    "the Ergies Crystal",
    "monsters",
    "desperation",
    "buckets and buckets of loot",
    "module functions",
    "Banhua's pants",
	"01's moral integrity",
    "Sailor Bamboo",
    "Xiaozheng Dalao",
    "well-fed Bear",
    "Falted Sish",
    "EdgeDemeril",
    "nil",     
    "Normality the Translator",
}
STRINGS.TASK = [[
	emmmmmmmmmmmm
]]
STRINGS.TASK1 = [[
This tutorial is inspired by the following books：
"I'll Check That at Night" "Will Do Once Finished My Meal"
"Isn't It Functional?" "Zzzzzzzzz"
"There Will Be an Update Very Soon, or So Have I Said"
"Bug Fixes are for Tomorrow"
]]
STRINGS.TASK2 = [[
[2. 29, 202x ]
[THE TERMINAL IS ATTEMPTING TO LINK UP WITH THE DATABASE. (4/5)]
---------------------------------------
[ATTEMPT FAILED DUE TO POOR SIGNAL.]
[REATTEMPTING... (5/5)]
---------------------------------------
[ATTEMPT FAILED DUE TO POOR SIGNAL.]
[THE TERMINAL HAS LOST THE SIGNAL.]
[REPEAT, SIGNAL IS LOST.]
[ENGAGING STATUS ASSESSING...]
[THE TERMINAL DEEMS THAT YOU HAVE ENTERED A TERRITORY OF BARBARISM.]
[THE TERMINAL DEEMS THAT 
YOU WILL DIE SOON DUE TO LACK OF SURVIVAL EXPERIENCE.]
[ACCIDENT RATE FOR K404 MODEL IS MERELY 0.0003%.]
[MATHEMATICAL PROBABILITY OF ROUTE DEVIATION 
CAUSED BY CRITICAL ANOMALY IS MERELY 0.0002%.]
]]
STRINGS.TASK3 = [[
[THE TERMINAL CONSULTED THESES FROM YOUR FORMER RESEARCHES.]
[THE TERMINAL AFFIRMS THEIR POTENTIAL HELPFULNESS.]
[THE TERMINAL SUGGESTS THAT YOU SHOULD ESTABLISH BASE STATIONS
IN ORDER TO SEEK TO GET IN TOUCH WITH THE SHINING WORLD.]
[THE TERMINAL DEDUCES THAT ELECTRICITY IS AN ESSENTIAL PART OF THE PLAN.]
[THE TERMINAL HAS FOUND A BLUEPRINT OF COMMUNICATION EQUIPMENT
FROM YOUR FORMER INVENTIONS.]
[ANALYZING SUBJECT...]
[THE TERMINAL DEEMS THAT THE EQUIPMENT IS OUTDATED YET PASSABLE.]
[THE TERMINAL SUGGESTS THAT YOU SHOULD COMMENCE GATHERING
NECESSARY MATERIALS TO CRAFT IT.]
]]
STRINGS.TASK4 = [[
[THE TERMINAL HAS CONSULTED ALL OF YOUR FORMER THESES.]
[THE TERMINAL DEEMS THAT
AN ECO-FRIENDLY METAL NAMED 'SEED' MIGHT BE VERY VERSATILE.]
[THE TERMINAL HAS NOTICED THAT
YOU HAVE DEVISED A INTEGRATED PROCESS FOR ITS MASS PRODUCTION.]
[THE TERMINAL SUGGESTS THAT
YOU SHOULD COMMENCE PREPARING THE METAL.]
[THE TERMINAL HOPES THAT
YOU STILL REMAIN MANIPULATIVE WHEN OUT OF LABORATORY.]
[ACCORDING TO YOUR THESIS,
YOU WILL NEED TO GATHER SOME METAL AND SEEDS FOR MATERIALS.]
]]
STRINGS.TASK5 = [[
Task：A Metal So Versatile
Requirement：Obtain a SEED ingot.
Introduction：You won't be able to last for long without it.
Preparation Process：
Open your crafting table.
Put the materials in the proper way and click the button.
Task rewards? Come on, don't be silly!
{Place the target item in your inventory so the Terminal may detect it.}
]]
STRINGS.TASK6 = [[
[THE TERMINAL DEEMS THAT
YOU HAVE DONE IT WELL ENOUGH FOR YOUR FIRST ATTEMPT.]
[NEVERTHELESS, A FEW INGOTS WON'T CHANGE A THING.]
[YOU WILL NEED TO MASS PRODUCE IT BY LARGE-SCALE PLANTING.]
[BUT PUT THAT ASIDE FOR NOW, THE TERMINAL SUGGESTS.]
[THE TERMINAL DEEMS THAT
YOU SHOULD COMMENCE ESTABLISHING FOOD SOURCES.]
[RELIABLE FOOD SOURCES ARE ESSENTIAL TO LONG-TERM SURVIVAL.]
[A BOTANIST'S WORKBENCH WILL BE OF USE.]
]]
STRINGS.TASK7 = [[
Task：Advanced Agriculture
Requirement：Craft a Botanist's Workbench
Introduction：You must eat to live.
Process of Crafting the Target Item：
Open your crafting table.
Put the materials in the proper way and click the button.
{Place the target item in your inventory so the Terminal may detect it.}
]]
STRINGS.TASK8 = [[
[THE TERMINAL DEEMS THAT
YOU MIGHT BE ABLE TO SUSTAIN YOURSELF FOR NOW.]
[THE TERMINAL IS CONFUSED ABOUT
THE INNATE DEFECTS OF THESE CROPS.]
[THEY CAN NOT BE TRANSPLANTED,
OR THEY WILL BE REDUCED TO PRIMITIVE STRAINS.]
[THE TERMINAL DEDUCED THAT
YOUR LAZINESS IN REDESIGNING GENE IS TO BLAME.]
[THE TERMINAL WARNS THAT
YOUR LAZINESS IS LIKELY BECOME AN OBSTRUCTION IN THE FUTURE.]
]]
STRINGS.TASK9 = [[
[THE TERMINAL SUGGESTS THAT
FOOD REFINEMENTS ARE ESSENTIAL FOR YOUR FRAGILE STOMACH.]
[THE TERMINAL DEDUCES THAT YOU WILL NEED ELECTRICITY.]
[THE TERMINAL SUGGESTS THAT
YOU SHOULD CRAFT A MANUAL GENERATOR.]
[THERMAL GENERATORS ARE MORE EFFICIENT
BUT YOU MAY NOT BE ABLE TO CRAFT IT AT THE MOMENT.]
[THE TERMINAL DEEMS THAT YOU WILL NEED BATTERIES
TO STORE SURPLUS ELECTRICITY.]
[ELECTRIC REPEATERS ARE GOOD CHOICES
FOR BOTH STORING AND ALLOCATING ELECTRICITY.]
]]
STRINGS.TASK10 = [[
Task：Electricity
Requirement：Craft a Electric Repeater
Introduction：Of course we need to store surplus electricity.
Process of Crafting the Target Item：
Open your crafting table.
Put the materials in the proper way and click the button.
{Place the target item in your inventory so the Terminal may detect it.}
]]
STRINGS.TASK11 = [[
Zzzzzzzzz...
]]
STRINGS.TASK12 = [[

]]
STRINGS.TASK13 = [[

]]
STRINGS.TASK14 = [[
[IT SEEMS THAT YOU HAVE MADE SOME 'SEED' SEED.]
[MAKE SURE TO PLANT THESE IN LEISURE.]
[YOU CAN CRAFT MORE MACHINES AS YOUR SEED INGOTS ACCUMULATE.]
[THE TERMINAL DEEMS THAT A SURVIVAL GENERATOR IS VITAL.]
]]
STRINGS.TASK15 = [[
Task：Dawn of Electricity
Requirement：Craft a Survival Generator
Introduction：Technologies are all about boiling water.
Process of Crafting the Target Item：
Open your crafting table.
Put the materials in the proper way and click the button.
{Place the target item in your inventory so the Terminal may detect it.}
]]
STRINGS.TASK16 = [[]]
STRINGS.TASK17 = [[]]
STRINGS.TASK18 = [[]]
STRINGS.TASK19 = [[]]
STRINGS.TASK20 = [[]]
STRINGS.TASK21 = [[]]
STRINGS.TASK22 = [[]]
STRINGS.TASK23 = [[]]
STRINGS.TASK24 = [[]]
STRINGS.TASK25 = [[]]
STRINGS.TASK26 = [[]]
STRINGS.TASK27 = [[]]
end